name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: 12
          postgresql db: fifo
          postgresql user: postgres
          postgresql password: postgres
      - name: Wait untill DB started (workaround of https://github.com/Harmon758/postgresql-action/issues/7)
        uses: jakejarvis/wait-action@v0.1.0
        with:
          time: '5s'
      - name: Migrations
        run: php artisan migrate
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
